# Form implementation generated from reading ui file 'C:\Users\ACER\PycharmProjects\KTLT\Exercise 59 21\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 70, 581, 51))
        self.label.setStyleSheet("color: rgb(85, 170, 255);\n"
"font: 57 20pt \"Poppins Medium\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(70, 140, 461, 181))
        self.groupBox.setObjectName("groupBox")
        self.label_n = QtWidgets.QLabel(parent=self.groupBox)
        self.label_n.setGeometry(QtCore.QRect(60, 40, 55, 21))
        self.label_n.setObjectName("label_n")
        self.label_k = QtWidgets.QLabel(parent=self.groupBox)
        self.label_k.setGeometry(QtCore.QRect(60, 80, 55, 21))
        self.label_k.setObjectName("label_k")
        self.lineEdit_n = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_n.setGeometry(QtCore.QRect(160, 40, 251, 22))
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.lineEdit_k = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_k.setGeometry(QtCore.QRect(160, 80, 251, 22))
        self.lineEdit_k.setObjectName("lineEdit_k")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 340, 81, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\ACER\\PycharmProjects\\KTLT\\Exercise 21\\icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 380, 461, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_a = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_a.setGeometry(QtCore.QRect(100, 50, 31, 21))
        self.label_a.setObjectName("label_a")
        self.label_b = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_b.setGeometry(QtCore.QRect(100, 90, 31, 21))
        self.label_b.setObjectName("label_b")
        self.lineEdit_a = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_a.setGeometry(QtCore.QRect(170, 50, 181, 22))
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.lineEdit_b = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_b.setGeometry(QtCore.QRect(170, 90, 181, 22))
        self.lineEdit_b.setObjectName("lineEdit_b")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Permulation Combination"))
        self.groupBox.setTitle(_translate("MainWindow", "Enter N and K:"))
        self.label_n.setText(_translate("MainWindow", "Enter N: "))
        self.label_k.setText(_translate("MainWindow", "Enter K: "))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Result:"))
        self.label_a.setText(_translate("MainWindow", "A="))
        self.label_b.setText(_translate("MainWindow", "B="))
