# Form implementation generated from reading ui file 'C:\Users\ACER\PycharmProjects\KTLT\Exercise 24\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_machine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_machine.setGeometry(QtCore.QRect(280, 250, 161, 20))
        self.lineEdit_machine.setObjectName("lineEdit_machine")
        self.lineEdit_player = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_player.setGeometry(QtCore.QRect(280, 300, 161, 20))
        self.lineEdit_player.setObjectName("lineEdit_player")
        self.pushButton_new = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_new.setGeometry(QtCore.QRect(250, 350, 93, 28))
        self.pushButton_new.setObjectName("pushButton_new")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 551, 411))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_random = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_random.setGeometry(QtCore.QRect(40, 330, 93, 28))
        self.pushButton_random.setObjectName("pushButton_random")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_exit.setGeometry(QtCore.QRect(420, 330, 93, 28))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label1 = QtWidgets.QLabel(parent=self.groupBox)
        self.label1.setGeometry(QtCore.QRect(40, 80, 81, 91))
        self.label1.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 0, 0);\n"
"font: 87 26pt \"Poppins Black\";")
        self.label1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label2.setGeometry(QtCore.QRect(240, 80, 81, 91))
        self.label2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 0, 0);\n"
"font: 87 26pt \"Poppins Black\";")
        self.label2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label3.setGeometry(QtCore.QRect(430, 80, 81, 91))
        self.label3.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 0, 0);\n"
"font: 87 26pt \"Poppins Black\";")
        self.label3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label3.setObjectName("label3")
        self.label_player = QtWidgets.QLabel(parent=self.groupBox)
        self.label_player.setGeometry(QtCore.QRect(140, 280, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_player.setFont(font)
        self.label_player.setObjectName("label_player")
        self.label_machine = QtWidgets.QLabel(parent=self.groupBox)
        self.label_machine.setGeometry(QtCore.QRect(140, 230, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_machine.setFont(font)
        self.label_machine.setObjectName("label_machine")
        self.groupBox.raise_()
        self.lineEdit_machine.raise_()
        self.lineEdit_player.raise_()
        self.pushButton_new.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_new.setText(_translate("MainWindow", "New Game"))
        self.groupBox.setTitle(_translate("MainWindow", "Random Game"))
        self.pushButton_random.setText(_translate("MainWindow", "Random"))
        self.pushButton_exit.setText(_translate("MainWindow", "End Game"))
        self.label1.setText(_translate("MainWindow", "7"))
        self.label2.setText(_translate("MainWindow", "7"))
        self.label3.setText(_translate("MainWindow", "7"))
        self.label_player.setText(_translate("MainWindow", "Player"))
        self.label_machine.setText(_translate("MainWindow", "Machine"))
