# Form implementation generated from reading ui file 'C:\Users\ACER\PycharmProjects\KTLT\Exercise 33\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(553, 408)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_array = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_array.setGeometry(QtCore.QRect(50, 50, 461, 31))
        self.lineEdit_array.setObjectName("lineEdit_array")
        self.lineEdit_result = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_result.setGeometry(QtCore.QRect(50, 120, 461, 31))
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_random = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_random.setGeometry(QtCore.QRect(50, 180, 221, 31))
        self.pushButton_random.setObjectName("pushButton_random")
        self.pushButton_find = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_find.setGeometry(QtCore.QRect(290, 180, 221, 31))
        self.pushButton_find.setObjectName("pushButton_find")
        self.pushButton_increment = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_increment.setGeometry(QtCore.QRect(290, 220, 221, 31))
        self.pushButton_increment.setObjectName("pushButton_increment")
        self.pushButton_sum = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_sum.setGeometry(QtCore.QRect(50, 220, 221, 31))
        self.pushButton_sum.setObjectName("pushButton_sum")
        self.pushButton_sort_ascend = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_sort_ascend.setGeometry(QtCore.QRect(290, 260, 221, 31))
        self.pushButton_sort_ascend.setObjectName("pushButton_sort_ascend")
        self.pushButton_count = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_count.setGeometry(QtCore.QRect(50, 260, 221, 31))
        self.pushButton_count.setObjectName("pushButton_count")
        self.pushButton_sort_descend = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_sort_descend.setGeometry(QtCore.QRect(290, 300, 221, 31))
        self.pushButton_sort_descend.setObjectName("pushButton_sort_descend")
        self.pushButton_sum_odd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_sum_odd.setGeometry(QtCore.QRect(50, 300, 221, 31))
        self.pushButton_sum_odd.setObjectName("pushButton_sum_odd")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 553, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Original Array: "))
        self.label_2.setText(_translate("MainWindow", "Result: "))
        self.pushButton_random.setText(_translate("MainWindow", "Random Array"))
        self.pushButton_find.setText(_translate("MainWindow", "Find smallest element"))
        self.pushButton_increment.setText(_translate("MainWindow", "increment double value"))
        self.pushButton_sum.setText(_translate("MainWindow", "Sum of Array"))
        self.pushButton_sort_ascend.setText(_translate("MainWindow", "Sort - Ascending"))
        self.pushButton_count.setText(_translate("MainWindow", "Count odd element"))
        self.pushButton_sort_descend.setText(_translate("MainWindow", "Sort - Descending"))
        self.pushButton_sum_odd.setText(_translate("MainWindow", "Sum of odd element"))
