# Form implementation generated from reading ui file 'C:\Users\ACER\PycharmProjects\KTLT\Exercise 124\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 620)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_employee = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_employee.setGeometry(QtCore.QRect(30, 60, 761, 371))
        self.tableWidget_employee.setObjectName("tableWidget_employee")
        self.tableWidget_employee.setColumnCount(0)
        self.tableWidget_employee.setRowCount(0)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 0, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtoExportAll = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtoExportAll.setGeometry(QtCore.QRect(30, 500, 101, 31))
        self.pushButtoExportAll.setObjectName("pushButtoExportAll")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 440, 131, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_Filter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Filter.setGeometry(QtCore.QRect(210, 440, 93, 31))
        self.pushButton_Filter.setObjectName("pushButton_Filter")
        self.pushButtonExportTop3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExportTop3.setGeometry(QtCore.QRect(150, 500, 151, 31))
        self.pushButtonExportTop3.setObjectName("pushButtonExportTop3")
        self.tableWidget_count = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_count.setGeometry(QtCore.QRect(510, 440, 256, 91))
        self.tableWidget_count.setObjectName("tableWidget_count")
        self.tableWidget_count.setColumnCount(0)
        self.tableWidget_count.setRowCount(0)
        self.pushButton_Count = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Count.setGeometry(QtCore.QRect(590, 540, 93, 28))
        self.pushButton_Count.setObjectName("pushButton_Count")
        self.pushButton_Add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Add.setGeometry(QtCore.QRect(320, 500, 93, 31))
        self.pushButton_Add.setObjectName("pushButton_Add")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Employee List"))
        self.pushButtoExportAll.setText(_translate("MainWindow", "Export all"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Year/Tester Role"))
        self.pushButton_Filter.setText(_translate("MainWindow", "Filter"))
        self.pushButtonExportTop3.setText(_translate("MainWindow", "Export TOP 3 oldest age"))
        self.pushButton_Count.setText(_translate("MainWindow", "Count by Role"))
        self.pushButton_Add.setText(_translate("MainWindow", "Add"))
